name: attendance-app
channels:
  - conda-forge
dependencies:
  - python
  - flask
  - keras
  - tensorflow
  - pymysql
  - mysql-connector-python
  - pip
  - pip:
      - opencv-python
      - opencv-contrib-python
      - flask_sqlalchemy
