name: attendance-app
channels:
  - conda-forge
dependencies:
  - python=3.11
  - flask
  - pymysql
  - mysql-connector-python
  - pip
  - pip:
      - tensorflow=2.15
      - opencv-python
      - opencv-python=4.8.0.74
      - flask_sqlalchemy
